service: etcd-main-client
namespace: <NAMESPACE>
labels:
  "app" : "etcd-statefulset"
  "role" : "main"
dependantpods:
- name: controlplane
  selector:
    matchExpressions:
    - key: garden.sapcloud.io/role
      operator: In
      values:
      - controlplane
    - key: role
      operator: NotIn
      values:
      - main