# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors.
#
# SPDX-License-Identifier: Apache-2.0

#namespace: <NAMESPACE>
probes:
- name: kube-apiserver
  probe:
    external:
      kubeconfigSecretName: kubeconfig-external
    internal:
      kubeconfigSecretName: kubeconfig-internal
  dependantScales:
  - scaleRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: kube-controller-manager
    replicas: 1
  - scaleRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: machine-controller-manager
    replicas: 1
    scaleUpDelay: 10
    scaleDownDelay: 0
