namespace: <NAMESPACE>
services:
  kube-apiserver:
    dependantPods:
    - name: controlplane
      selector:
        matchExpressions:
        - key: garden.sapcloud.io/role
          operator: In
          values:
          - controlplane
        - key: role
          operator: NotIn
          values:
          - main
        - key: role
          operator: NotIn
          values:
          - apiserver
  etcd-main-client:
    dependantPods:
    - name: controlplane
      selector:
        matchExpressions:
        - key: garden.sapcloud.io/role
          operator: In
          values:
          - controlplane
        - key: role
          operator: In
          values:
          - apiserver
