service: etcd-main-client
namespace: shoot--dev--i308301-2
labels:
  "app" : "etcd-statefulset"
  "role" : "main"
dependantpods:
- name: controlplane
  selector:
    matchExpressions:
    - key: garden.sapcloud.io/role
      operator: In
      values:
      - controlplane
    - key: role
      operator: In
      values:
      - cloud-controller-manager
      - addon-manager
      - apiserver
      - controller-manager
      - scheduler
- name: aws-lb-readvertiser
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - aws-lb-readvertiser
    - key: garden.sapcloud.io/role
      operator: In
      values:
      - controlplane